// actionTypes.js
export const GET_RESERVATIONS_PENDING = 'GET_RESERVATIONS_PENDING';
export const GET_RESERVATIONS_SUCCESS = 'GET_RESERVATIONS_SUCCESS';
export const GET_RESERVATIONS_ERROR = 'GET_RESERVATIONS_ERROR';